### ISSUE TITLE
SFCommandBuilder.java can't find ApplicationManifest.xml when running the build in Jenkins Slave

### ISSUE THREAD

**Issue by abalogh** [jenkinsci/service-fabric-plugin#16] opened 2018-09-17 11:42 UTC
I get the following error when I try to deploy  a Service Fabric Application:
java.lang.RuntimeException: /mnt/resource/jenkins/workspace/Deploy_My_Api/service-fabric/MyApi/ApplicationManifest.xml (No such file or directory)
	at com.microsoft.jenkins.servicefabric.command.SFCommandBuilder.checkTargetApplicationManifestVersion(SFCommandBuilder.java:166)
	at com.microsoft.jenkins.servicefabric.command.SFCommandBuilder.buildCommands(SFCommandBuilder.java:73)
	at com.microsoft.jenkins.servicefabric.ServiceFabricPublishStep.doRunStep(ServiceFabricPublishStep.java:172)

The ApplicationManifest.xml file is definitely there in the workspace if I add a previuos step in Jenkins to list the files in that directory it will show it.

I think the problem is that the Deploy Jenkins job is running on a Jenkins Slave. 
I checked the source code and I see the path is resolved as:
 newFilePath = workspace.child(filePath).getRemote()

**Comment by rapatchi** [comment] 2018-09-17 12:30
@abalogh , Thanks for reporting this. 
Could  you report back on what you have configured in the "Path to Application Manifest" field ?.

**Comment by abalogh** [comment] 2018-09-17 14:11
@rapatchi I tried with two cases, relative path in "Path to Application Manifest":
./service-fabric/MyApi/ApplicationManifest.xml 
or
service-fabric/MyApi/ApplicationManifest.xml 

then with full absolute path:
/mnt/resource/jenkins/workspace/Deploy_My_Api/service-fabric/MyApi/ApplicationManifest.xml

In both cases same error, please note the path reported as "not found" with Exception is actually correct if I do a bash command and do: "ls -l"

**Comment by rapatchi** [comment] 2018-09-21 10:42
Hi @abalogh, 

Sorry for the delayed reply. I was not able to reproduce the issue you have mentioned here. 

But in past i remember that i was getting this issue if there were spaces left out at the end of the string you mention in the "Path to Application Manifest" field. Let me know if this is the issue.

**Comment by rapatchi** [comment] 2018-11-19 04:08
Closing this issue. Please reopen if you are still facing this issue.

**Closed by rapatchi** 2018-11-19 04:08 UTC
